import json
from pathlib import Path
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)


class DossierGenerator:
    """
    Module 15: Dossier Generator.

    Input:
        Ranking output generated by RankingEngine.

    Output:
        PDF dossier with patient ID, ranking summary, top ranked trials,
        score breakdown, criteria summary, reasons, warnings, flags and trial metadata.

    This module does not calculate scores.
    It only formats already computed information into a readable PDF.
    """

    def _register_fonts(self):
        """
        Register local project fonts for PDF generation.

        Expected folder:
            src/fonts/

        Expected files:
            Inter-VariableFont_opsz,wght.ttf
            Inter-Italic-VariableFont_opsz,wght.ttf
            Montserrat-VariableFont_wght.ttf
            Montserrat-Italic-VariableFont_wght.ttf
        """

        fonts_dir = Path(__file__).parent / "fonts"

        font_files = {
            "Inter": fonts_dir / "Inter-VariableFont_opsz,wght.ttf",
            "Inter-Italic": fonts_dir / "Inter-Italic-VariableFont_opsz,wght.ttf",
            "Montserrat": fonts_dir / "Montserrat-VariableFont_wght.ttf",
            "Montserrat-Italic": fonts_dir / "Montserrat-Italic-VariableFont_wght.ttf",
        }

        for font_name, font_path in font_files.items():
            if font_path.exists():
                pdfmetrics.registerFont(TTFont(font_name, str(font_path)))

        self.font_body = (
            "Inter"
            if font_files["Inter"].exists()
            else "Helvetica"
        )

        self.font_body_italic = (
            "Inter-Italic"
            if font_files["Inter-Italic"].exists()
            else "Helvetica-Oblique"
        )

        self.font_title = (
            "Montserrat"
            if font_files["Montserrat"].exists()
            else "Helvetica-Bold"
        )

        self.font_title_italic = (
            "Montserrat-Italic"
            if font_files["Montserrat-Italic"].exists()
            else "Helvetica-Oblique"
        )

    def __init__(self):
        self._register_fonts()
        self.styles = getSampleStyleSheet()

        self.title_style = ParagraphStyle(
            name="DossierTitle",
            parent=self.styles["Title"],
            fontName=self.font_title,
            fontSize=20,
            leading=24,
            textColor=colors.HexColor("#003369"),
            spaceAfter=12,
        )

        self.subtitle_style = ParagraphStyle(
            name="DossierSubtitle",
            parent=self.styles["BodyText"],
            fontName=self.font_body,
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#334E68"),
            spaceAfter=10,
        )

        self.section_style = ParagraphStyle(
            name="SectionTitle",
            parent=self.styles["Heading2"],
            fontName=self.font_title,
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#003369"),
            spaceBefore=12,
            spaceAfter=8,
        )

        self.trial_title_style = ParagraphStyle(
            name="TrialTitle",
            parent=self.styles["Heading3"],
            fontName=self.font_title,
            fontSize=12,
            leading=15,
            textColor=colors.HexColor("#003369"),
            spaceBefore=10,
            spaceAfter=6,
        )

        self.normal_style = ParagraphStyle(
            name="NormalText",
            parent=self.styles["BodyText"],
            fontName=self.font_body,
            fontSize=9,
            leading=12,
            alignment=TA_LEFT,
        )

        self.small_style = ParagraphStyle(
            name="SmallText",
            parent=self.styles["BodyText"],
            fontName=self.font_body,
            fontSize=8,
            leading=10,
            alignment=TA_LEFT,
        )

    def load_json(self, input_path):
        input_path = Path(input_path)

        with input_path.open("r", encoding="utf-8") as file:
            return json.load(file)

    def generate_pdf(self, ranking_output, output_path, top_k=None):
        """
        Generate a PDF dossier from RankingEngine output.

        Expected RankingEngine output:

        {
            "patient_id": "...",
            "ranking_status": "completed",
            "ranking_version": "ranking_engine_v1",
            "ranked_trials": [...],
            "summary": {...},
            "flags": [...]
        }
        """

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=A4,
            rightMargin=1.4 * cm,
            leftMargin=1.4 * cm,
            topMargin=1.4 * cm,
            bottomMargin=1.4 * cm,
        )

        story = []

        self._add_header(story, ranking_output)
        self._add_ranking_summary(story, ranking_output)
        self._add_global_flags(story, ranking_output)

        ranked_trials = ranking_output.get("ranked_trials") or []

        if top_k is not None:
            ranked_trials = ranked_trials[:top_k]

        if not ranked_trials:
            story.append(Paragraph("No ranked trials available.", self.normal_style))
        else:
            story.append(Paragraph("Top ranked trials", self.section_style))

            for index, ranked_trial in enumerate(ranked_trials):
                if index > 0:
                    story.append(PageBreak())

                self._add_ranked_trial(story, ranked_trial)

        doc.build(story)

        return output_path

    def _add_header(self, story, ranking_output):
        story.append(Paragraph("ClinicalMatch Trial Dossier", self.title_style))

        story.append(
            Paragraph(
                "Generated from Ranking Engine output. This dossier summarizes ranked trials, "
                "scores, eligibility signals, criterion summaries and ranking reasons.",
                self.subtitle_style,
            )
        )

        rows = [
            ["Patient ID", ranking_output.get("patient_id", "-")],
            ["Ranking status", ranking_output.get("ranking_status", "-")],
            ["Ranking version", ranking_output.get("ranking_version", "-")],
        ]

        story.append(self._key_value_table(rows))
        story.append(Spacer(1, 10))

    def _add_ranking_summary(self, story, ranking_output):
        ranking_summary = (
            ranking_output.get("summary")
            or ranking_output.get("ranking_summary")
            or {}
        )

        ranked_trials = ranking_output.get("ranked_trials") or []

        story.append(Paragraph("Ranking summary", self.section_style))

        rows = [
            ["Total trials", ranking_summary.get("total_trials", len(ranked_trials))],
            ["Ranked trials", ranking_summary.get("ranked_trials", len(ranked_trials))],
            ["Excellent matches", ranking_summary.get("excellent_matches", "-")],
            ["Good matches", ranking_summary.get("good_matches", "-")],
            ["Possible matches", ranking_summary.get("possible_matches", "-")],
            ["Low matches", ranking_summary.get("low_matches", "-")],
            ["Trials with blockers", ranking_summary.get("trials_with_blockers", "-")],
            [
                "Trials with unknown critical",
                ranking_summary.get("trials_with_unknown_critical", "-"),
            ],
            ["Trials with errors", ranking_summary.get("trials_with_errors", "-")],
            ["Best score", self._format_number(ranking_summary.get("best_score"))],
            ["Median score", self._format_number(ranking_summary.get("median_score"))],
            ["Worst score", self._format_number(ranking_summary.get("worst_score"))],
        ]

        story.append(self._key_value_table(rows))
        story.append(Spacer(1, 10))

    def _add_global_flags(self, story, ranking_output):
        flags = ranking_output.get("flags") or []

        if not flags:
            return

        story.append(Paragraph("Global ranking flags", self.section_style))

        data = [
            [
                Paragraph("Type", self.small_style),
                Paragraph("Severity", self.small_style),
                Paragraph("Message", self.small_style),
            ]
        ]

        for flag in flags:
            data.append(
                [
                    Paragraph(self._safe(flag.get("type")), self.small_style),
                    Paragraph(self._safe(flag.get("severity")), self.small_style),
                    Paragraph(self._safe(flag.get("message")), self.small_style),
                ]
            )

        table = Table(
            data,
            colWidths=[4.0 * cm, 3.0 * cm, 10.4 * cm],
            repeatRows=1,
        )

        table.setStyle(self._default_table_style())
        story.append(table)
        story.append(Spacer(1, 10))

    def _add_ranked_trial(self, story, ranked_trial):
        rank = ranked_trial.get("rank", "-")
        nct_id = ranked_trial.get("nct_id") or ranked_trial.get("trial_id") or "-"

        trial = ranked_trial.get("trial") or {}

        title = (
            trial.get("brief_title")
            or trial.get("title")
            or trial.get("official_title")
            or self._get_from_identification(trial, "brief_title")
            or self._get_from_identification(trial, "official_title")
            or "Untitled trial"
        )

        story.append(
            Paragraph(
                f"#{self._safe(rank)} - {self._safe(nct_id)}",
                self.trial_title_style,
            )
        )

        story.append(
            Paragraph(
                f"<b>{self._safe(title)}</b>",
                self.normal_style,
            )
        )

        story.append(Spacer(1, 6))

        self._add_trial_metadata(story, ranked_trial)
        self._add_score_breakdown(story, ranked_trial)
        self._add_criteria_summary(story, ranked_trial)
        self._add_reasons(story, ranked_trial)
        self._add_trial_warnings(story, ranked_trial)
        self._add_optional_criteria_scores(story, ranked_trial)
        self._add_optional_criteria_evaluations(story, ranked_trial)
        self._add_optional_missing_questions(story, ranked_trial)

    def _add_trial_metadata(self, story, ranked_trial):
        trial = ranked_trial.get("trial") or {}

        conditions = (
            trial.get("conditions")
            or trial.get("condition")
            or self._get_nested_value(trial, ["conditionsModule", "conditions"])
            or []
        )

        locations = (
            trial.get("locations")
            or self._extract_locations_from_trial(trial)
            or []
        )

        if not isinstance(conditions, list):
            conditions = [conditions]

        if not isinstance(locations, list):
            locations = [locations]

        rows = [
            ["Rank", ranked_trial.get("rank", "-")],
            [
                "NCT ID",
                ranked_trial.get("nct_id") or ranked_trial.get("trial_id") or "-",
            ],
            ["Score", self._format_number(ranked_trial.get("score"))],
            ["Ranking bucket", ranked_trial.get("ranking_bucket", "-")],
            [
                "Phase",
                trial.get("phase")
                or self._get_nested_value(trial, ["designModule", "phases"])
                or "-",
            ],
            [
                "Status",
                trial.get("overall_status")
                or trial.get("status")
                or self._get_nested_value(trial, ["statusModule", "overallStatus"])
                or "-",
            ],
            [
                "Conditions",
                ", ".join([str(item) for item in conditions]) if conditions else "-",
            ],
            [
                "Locations",
                ", ".join([str(item) for item in locations]) if locations else "-",
            ],
        ]

        story.append(Paragraph("Trial identification", self.section_style))
        story.append(self._key_value_table(rows))
        story.append(Spacer(1, 8))

    def _add_score_breakdown(self, story, ranked_trial):
        breakdown = ranked_trial.get("score_breakdown") or {}

        story.append(Paragraph("Score breakdown", self.section_style))

        rows = [
            ["Weighted score sum", self._format_number(breakdown.get("weighted_score_sum"))],
            [
                "Max weighted score sum",
                self._format_number(breakdown.get("max_weighted_score_sum")),
            ],
            ["Base score ratio", self._format_number(breakdown.get("base_score_ratio"))],
            ["Base score", self._format_number(breakdown.get("base_score"))],
            [
                "Penalty multiplier",
                self._format_number(breakdown.get("penalty_multiplier")),
            ],
            [
                "Bonus multiplier",
                self._format_number(breakdown.get("bonus_multiplier")),
            ],
            ["Final score", self._format_number(breakdown.get("final_score"))],
        ]

        story.append(self._key_value_table(rows))
        story.append(Spacer(1, 8))

    def _add_criteria_summary(self, story, ranked_trial):
        summary = ranked_trial.get("summary") or {}

        story.append(Paragraph("Criteria summary", self.section_style))

        rows = [
            ["Total criteria", summary.get("total_criteria", "-")],
            ["Met", summary.get("met", "-")],
            ["Not met", summary.get("not_met", "-")],
            ["Unknown", summary.get("unknown", "-")],
            ["Not applicable", summary.get("not_applicable", "-")],
            ["Evaluation error", summary.get("evaluation_error", "-")],
            ["Inclusion total", summary.get("inclusion_total", "-")],
            ["Inclusion met", summary.get("inclusion_met", "-")],
            ["Inclusion not met", summary.get("inclusion_not_met", "-")],
            ["Inclusion unknown", summary.get("inclusion_unknown", "-")],
            ["Exclusion total", summary.get("exclusion_total", "-")],
            ["Exclusion triggered", summary.get("exclusion_triggered", "-")],
            ["Exclusion not triggered", summary.get("exclusion_not_triggered", "-")],
            ["Exclusion unknown", summary.get("exclusion_unknown", "-")],
            ["Hard fail count", summary.get("hard_fail_count", "-")],
            ["Unknown hard count", summary.get("unknown_hard_count", "-")],
            ["Soft unknown count", summary.get("soft_unknown_count", "-")],
            ["Known coverage", self._format_number(summary.get("known_coverage"))],
        ]

        story.append(self._key_value_table(rows))
        story.append(Spacer(1, 8))

    def _add_reasons(self, story, ranked_trial):
        reasons = ranked_trial.get("reasons") or []

        story.append(Paragraph("Ranking reasons", self.section_style))

        if not reasons:
            story.append(Paragraph("No ranking reasons provided.", self.normal_style))
            story.append(Spacer(1, 8))
            return

        for reason in reasons:
            story.append(Paragraph(f"- {self._safe(reason)}", self.normal_style))

        story.append(Spacer(1, 8))

    def _add_trial_warnings(self, story, ranked_trial):
        warnings = ranked_trial.get("warnings") or []

        if not warnings:
            return

        story.append(Paragraph("Trial warnings", self.section_style))

        for warning in warnings:
            story.append(Paragraph(f"- {self._safe(warning)}", self.normal_style))

        story.append(Spacer(1, 8))

    def _add_optional_criteria_scores(self, story, ranked_trial):
        breakdown = ranked_trial.get("score_breakdown") or {}
        criterion_scores = breakdown.get("criterion_scores") or []

        if not criterion_scores:
            return

        story.append(Paragraph("Criterion score contributions", self.section_style))

        data = [
            [
                Paragraph("Criterion ID", self.small_style),
                Paragraph("Type", self.small_style),
                Paragraph("Status", self.small_style),
                Paragraph("Hardness", self.small_style),
                Paragraph("Category", self.small_style),
                Paragraph("Contribution", self.small_style),
            ]
        ]

        for criterion in criterion_scores:
            data.append(
                [
                    Paragraph(self._safe(criterion.get("criterion_id")), self.small_style),
                    Paragraph(self._safe(criterion.get("criterion_type")), self.small_style),
                    Paragraph(self._safe(criterion.get("evaluation_status")), self.small_style),
                    Paragraph(self._safe(criterion.get("hardness")), self.small_style),
                    Paragraph(self._safe(criterion.get("category")), self.small_style),
                    Paragraph(
                        self._format_number(criterion.get("contribution_ratio")),
                        self.small_style,
                    ),
                ]
            )

        table = Table(
            data,
            colWidths=[
                3.2 * cm,
                2.1 * cm,
                2.4 * cm,
                2.2 * cm,
                3.5 * cm,
                2.4 * cm,
            ],
            repeatRows=1,
        )

        table.setStyle(self._default_table_style())
        story.append(table)
        story.append(Spacer(1, 8))

    def _add_optional_criteria_evaluations(self, story, ranked_trial):
        criteria = ranked_trial.get("criteria_evaluations") or []

        if not criteria:
            return

        story.append(Paragraph("Detailed criteria evaluations", self.section_style))

        data = [
            [
                Paragraph("Criterion", self.small_style),
                Paragraph("Type", self.small_style),
                Paragraph("Status", self.small_style),
                Paragraph("Patient value", self.small_style),
                Paragraph("Evidence", self.small_style),
                Paragraph("Confidence", self.small_style),
            ]
        ]

        for criterion in criteria:
            data.append(
                [
                    Paragraph(self._safe(criterion.get("raw_text")), self.small_style),
                    Paragraph(self._safe(criterion.get("type")), self.small_style),
                    Paragraph(self._safe(criterion.get("status")), self.small_style),
                    Paragraph(self._safe(criterion.get("patient_value")), self.small_style),
                    Paragraph(self._safe(criterion.get("evidence")), self.small_style),
                    Paragraph(
                        self._format_number(criterion.get("confidence")),
                        self.small_style,
                    ),
                ]
            )

        table = Table(
            data,
            colWidths=[
                5.0 * cm,
                2.0 * cm,
                2.3 * cm,
                2.5 * cm,
                4.0 * cm,
                1.8 * cm,
            ],
            repeatRows=1,
        )

        table.setStyle(self._default_table_style())
        story.append(table)
        story.append(Spacer(1, 8))

    def _add_optional_missing_questions(self, story, ranked_trial):
        questions = ranked_trial.get("missing_questions") or []

        if not questions:
            return

        story.append(Paragraph("Missing information questions", self.section_style))

        data = [
            [
                Paragraph("Priority", self.small_style),
                Paragraph("Attribute", self.small_style),
                Paragraph("Question", self.small_style),
                Paragraph("Impact", self.small_style),
            ]
        ]

        for question in questions:
            data.append(
                [
                    Paragraph(self._safe(question.get("priority")), self.small_style),
                    Paragraph(self._safe(question.get("attribute")), self.small_style),
                    Paragraph(self._safe(question.get("question")), self.small_style),
                    Paragraph(
                        self._format_number(question.get("impact_score")),
                        self.small_style,
                    ),
                ]
            )

        table = Table(
            data,
            colWidths=[2.2 * cm, 3.0 * cm, 9.0 * cm, 2.0 * cm],
            repeatRows=1,
        )

        table.setStyle(self._default_table_style())
        story.append(table)
        story.append(Spacer(1, 8))

    def _key_value_table(self, rows):
        data = []

        for key, value in rows:
            data.append(
                [
                    Paragraph(f"<b>{self._safe(key)}</b>", self.small_style),
                    Paragraph(self._safe(value), self.small_style),
                ]
            )

        table = Table(
            data,
            colWidths=[4.4 * cm, 13.0 * cm],
        )

        table.setStyle(
            TableStyle(
                [
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D9E2EC")),
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EDF4FB")),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                ]
            )
        )

        return table

    def _default_table_style(self):
        return TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#003369")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D9E2EC")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 5),
                ("RIGHTPADDING", (0, 0), (-1, -1), 5),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                (
                    "ROWBACKGROUNDS",
                    (0, 1),
                    (-1, -1),
                    [colors.white, colors.HexColor("#F7FAFC")],
                ),
            ]
        )

    def _safe(self, value):
        if value is None:
            return "-"

        text = str(value)

        if text.strip() == "":
            return "-"

        return escape(text)

    def _format_number(self, value):
        if value is None:
            return "-"

        try:
            return f"{float(value):.2f}"
        except (TypeError, ValueError):
            return self._safe(value)

    def _get_nested_value(self, data, path):
        current = data

        for key in path:
            if not isinstance(current, dict):
                return None

            current = current.get(key)

            if current is None:
                return None

        return current

    def _get_from_identification(self, trial, key):
        identification = trial.get("identification")

        if isinstance(identification, dict):
            return identification.get(key)

        protocol_section = trial.get("protocolSection")

        if isinstance(protocol_section, dict):
            identification_module = protocol_section.get("identificationModule")

            if isinstance(identification_module, dict):
                return identification_module.get(key)

        return None

    def _extract_locations_from_trial(self, trial):
        locations = []

        direct_locations = trial.get("locations")

        if isinstance(direct_locations, list):
            return direct_locations

        contacts_locations = self._get_nested_value(
            trial,
            ["contactsLocationsModule", "locations"],
        )

        if isinstance(contacts_locations, list):
            for location in contacts_locations:
                if not isinstance(location, dict):
                    continue

                city = location.get("city")
                country = location.get("country")
                facility = location.get("facility")

                parts = [
                    item
                    for item in [facility, city, country]
                    if isinstance(item, str) and item.strip()
                ]

                if parts:
                    locations.append(", ".join(parts))

        return locations